#version 450
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform writeonly image2D result_image;

void	main()
{
	vec3	color;
	ivec2	dim = imageSize(result_image);
	vec2	uv = vec2(gl_GlobalInvocationID.xy) / dim;

	color = vec3(0.0, 1.0, 0.0);
	imageStore(result_image, ivec2(gl_GlobalInvocationID.xy), vec4(color, 1.0));
}
